root: ./

structure:  
  readme: README.md  
  summary: SUMMARY.md

redirects:  
  setup/instance-configuration/google-login: setup/instance-configuration/single-sign-on-sso/google-login.md
  setup/instance-configuration/github-login: setup/instance-configuration/single-sign-on-sso/github-login.md
